// <auto-generated />
using System;
using Examen.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen.Infrastructure.Migrations
{
    [DbContext(typeof(ExamenContext))]
    [Migration("20240507222531_first migration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Banque", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Banques");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Compte", b =>
                {
                    b.Property<string>("NumeroCompte")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BanqueFk")
                        .HasColumnType("int");

                    b.Property<string>("Proprietaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Solde")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("banqueCode")
                        .HasColumnType("int");

                    b.HasKey("NumeroCompte");

                    b.HasIndex("banqueCode");

                    b.ToTable("Comptes");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.DAB", b =>
                {
                    b.Property<string>("DABId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Loacalisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DABId");

                    b.ToTable("DABs");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Transaction", b =>
                {
                    b.Property<string>("NumeroCompteFk")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DABFk")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<double>("Montant")
                        .HasColumnType("float");

                    b.HasKey("NumeroCompteFk", "DABFk", "Date");

                    b.HasIndex("DABFk");

                    b.ToTable("Transactions");

                    b.HasDiscriminator<string>("Descriminator").HasValue("H");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.TransacationTransfert", b =>
                {
                    b.HasBaseType("Examen.ApplicationCore.Domain.Transaction");

                    b.Property<string>("NumeroCompte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("T");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.TransactionRetarit", b =>
                {
                    b.HasBaseType("Examen.ApplicationCore.Domain.Transaction");

                    b.Property<bool>("AutreAgence")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("R");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Compte", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.Banque", "banque")
                        .WithMany("Comptes")
                        .HasForeignKey("banqueCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("banque");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Transaction", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.DAB", "DAB")
                        .WithMany("Transactions")
                        .HasForeignKey("DABFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examen.ApplicationCore.Domain.Compte", "Compte")
                        .WithMany("Transactions")
                        .HasForeignKey("NumeroCompteFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");

                    b.Navigation("DAB");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Banque", b =>
                {
                    b.Navigation("Comptes");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Compte", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.DAB", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
